import { img, type City } from "./data";

// PLACEHOLDER: inventario de ejemplo. Año, kilometraje, color, código y tarifa deben
// reemplazarse por los datos reales de cada unidad.

export type UnitType = "auto" | "suv" | "pickup";

export type Unit = {
  code: string;
  model: string;
  type: UnitType;
  year: number;
  km: number;
  city: City;
  gearbox: "Automática" | "Mecánica";
  fuel: "Gasolina" | "Diésel" | "Híbrido";
  drive: string;
  seats: number;
  engine: string;
  cargo: { label: string; value: string };
  color: string;
  price: number;
  features: [string, string, string];
  image: string;
  position?: string;
};

export const TYPE_LABEL: Record<UnitType, string> = { auto: "Automóvil", suv: "SUV", pickup: "Pick-up" };

export const INVENTORY: Unit[] = [
  {
    code: "TR-101",
    model: "Kia Picanto",
    type: "auto",
    year: 2024,
    km: 18200,
    city: "Bogotá",
    gearbox: "Automática",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "1.25 L",
    cargo: { label: "Maletero", value: "255 L" },
    color: "Amarillo",
    price: 2_300_000,
    features: ["Apple CarPlay y Android Auto", "Cámara de reversa", "Aire acondicionado"],
    image: img("photo-1628066985934-0e1953425c22", 1200),
    position: "40% 60%",
  },
  {
    code: "TR-102",
    model: "Mazda 2 Hatchback",
    type: "auto",
    year: 2023,
    km: 26500,
    city: "Medellín",
    gearbox: "Automática",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "1.5 L",
    cargo: { label: "Maletero", value: "280 L" },
    color: "Rojo",
    price: 2_800_000,
    features: ["Sensores de parqueo", "Control crucero", "Apple CarPlay y Android Auto"],
    image: img("photo-1776802740772-dcfefd9e8e26", 1400),
    position: "18% 80%",
  },
  {
    code: "TR-103",
    model: "Mazda 3 Hatchback",
    type: "auto",
    year: 2024,
    km: 9800,
    city: "Bogotá",
    gearbox: "Automática",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "2.0 L",
    cargo: { label: "Maletero", value: "334 L" },
    color: "Gris",
    price: 3_600_000,
    features: ["Control crucero adaptativo", "Cámara de reversa", "Sensores de parqueo"],
    image: img("photo-1599491143816-8c1ea12a4e06", 1200),
    position: "55% 60%",
  },
  {
    code: "TR-201",
    model: "Renault Duster",
    type: "suv",
    year: 2023,
    km: 31000,
    city: "Cali",
    gearbox: "Mecánica",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "1.6 L",
    cargo: { label: "Maletero", value: "475 L" },
    color: "Verde",
    price: 3_900_000,
    features: ["Pantalla táctil", "Sensores de parqueo", "Aire acondicionado"],
    image: img("photo-1658504010272-0ee9efe72239", 1200),
    position: "50% 60%",
  },
  {
    code: "TR-202",
    model: "Mazda CX-5",
    type: "suv",
    year: 2024,
    km: 12400,
    city: "Medellín",
    gearbox: "Automática",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "2.0 L",
    cargo: { label: "Maletero", value: "442 L" },
    color: "Blanco",
    price: 5_900_000,
    features: ["Control crucero adaptativo", "Cámara de reversa", "Apple CarPlay y Android Auto"],
    image: img("photo-1643142311296-304953706775", 1200),
    position: "50% 60%",
  },
  {
    code: "TR-203",
    model: "Kia Sportage",
    type: "suv",
    year: 2024,
    km: 7500,
    city: "Bogotá",
    gearbox: "Automática",
    fuel: "Gasolina",
    drive: "4x2",
    seats: 5,
    engine: "2.0 L",
    cargo: { label: "Maletero", value: "543 L" },
    color: "Gris",
    price: 5_600_000,
    features: ["Pantalla panorámica", "Cámara de reversa", "Carga inalámbrica"],
    image: img("photo-1688893287874-ac7fbd686c24", 1200),
    position: "50% 60%",
  },
  {
    code: "TR-204",
    model: "Toyota RAV4",
    type: "suv",
    year: 2023,
    km: 21000,
    city: "Bucaramanga",
    gearbox: "Automática",
    fuel: "Híbrido",
    drive: "AWD",
    seats: 5,
    engine: "2.5 L híbrido",
    cargo: { label: "Maletero", value: "580 L" },
    color: "Blanco",
    price: 6_400_000,
    features: ["Control crucero adaptativo", "Cámara de reversa", "Apple CarPlay y Android Auto"],
    image: img("photo-1617600346256-af3cd5b16a4d", 1200),
    position: "50% 55%",
  },
  {
    code: "TR-205",
    model: "Toyota Fortuner",
    type: "suv",
    year: 2023,
    km: 28000,
    city: "Bucaramanga",
    gearbox: "Automática",
    fuel: "Diésel",
    drive: "4x4",
    seats: 7,
    engine: "2.8 L",
    cargo: { label: "Tercera fila", value: "Abatible" },
    color: "Plata",
    price: 7_800_000,
    features: ["Siete puestos", "Cámara de reversa", "Control de descenso"],
    image: img("photo-1670054953044-2605dbd0d747", 1200),
    position: "60% 60%",
  },
  {
    code: "TR-206",
    model: "Toyota Land Cruiser Prado",
    type: "suv",
    year: 2024,
    km: 11000,
    city: "Bogotá",
    gearbox: "Automática",
    fuel: "Diésel",
    drive: "4x4",
    seats: 7,
    engine: "2.8 L",
    cargo: { label: "Tercera fila", value: "Abatible" },
    color: "Negro",
    price: 10_500_000,
    features: ["Siete puestos", "Cámaras 360°", "Asientos en cuero"],
    image: img("photo-1630826362226-a509049bcdbf", 1200),
    position: "50% 58%",
  },
  {
    code: "TR-301",
    model: "Toyota Hilux",
    type: "pickup",
    year: 2024,
    km: 15000,
    city: "Bucaramanga",
    gearbox: "Automática",
    fuel: "Diésel",
    drive: "4x4",
    seats: 5,
    engine: "2.8 L",
    cargo: { label: "Carga útil", value: "1.000 kg" },
    color: "Blanco",
    price: 6_900_000,
    features: ["Doble cabina", "Cámara de reversa", "Control de descenso"],
    image: img("photo-1759213281196-6c5e463b3021", 1200),
    position: "50% 60%",
  },
  {
    code: "TR-302",
    model: "Toyota Hilux",
    type: "pickup",
    year: 2023,
    km: 34000,
    city: "Medellín",
    gearbox: "Mecánica",
    fuel: "Diésel",
    drive: "4x4",
    seats: 5,
    engine: "2.4 L",
    cargo: { label: "Carga útil", value: "1.000 kg" },
    color: "Gris",
    price: 6_300_000,
    features: ["Doble cabina", "Barra antivuelco", "Aire acondicionado"],
    image: img("photo-1631377875413-b1e3e660bfa2", 1200),
    position: "50% 65%",
  },
  {
    code: "TR-303",
    model: "Ford Ranger",
    type: "pickup",
    year: 2024,
    km: 9000,
    city: "Cali",
    gearbox: "Automática",
    fuel: "Diésel",
    drive: "4x4",
    seats: 5,
    engine: "2.0 L biturbo",
    cargo: { label: "Carga útil", value: "950 kg" },
    color: "Gris",
    price: 7_200_000,
    features: ["Doble cabina", "Modos de manejo todoterreno", "Apple CarPlay y Android Auto"],
    image: img("photo-1677739455846-2467604ea8b6", 1200),
    position: "50% 55%",
  },
];

export const kmFmt = (n: number) => n.toLocaleString("es-CO") + " km";

export const unitMessage = (u: Unit) =>
  `Hola, quiero cotizar la renta mensual de la unidad ${u.code}: ${u.model} ${u.year}, ${u.gearbox.toLowerCase()}, ` +
  `${u.color.toLowerCase()}, en ${u.city}. Vi la tarifa de $${u.price.toLocaleString("es-CO")} al mes + IVA en el inventario.`;
